export interface Flight {
    "fromAirport": string;
    "fromCountry": string;
    "toAirport": string;
    "toCountry": string;
    "flightCompany": string;
    "flightNumber": string;
    "departureDate": string;
    "arrivalDate": string;
    "roundTrip": boolean;
    "price": number;
    "seats": {
        "seatRowA": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        };
        "seatRowB": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        };
        "seatRowC": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        };
        "seatRowD": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        };
        "seatRowE": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        };
        "seatRowF": {
            "seat1": boolean;
            "seat2": boolean;
            "seat3": boolean;
            "seat4": boolean;
            "seat5": boolean;
            "seat6": boolean;
            "seat7": boolean;
            "seat8": boolean;
            "seat9": boolean;
            "seat10": boolean;
            "seat11": boolean;
            "seat12": boolean;
            "seat13": boolean;
            "seat14": boolean;
            "seat15": boolean;
            "seat16": boolean;
            "seat17": boolean;
            "seat18": boolean;
            "seat19": boolean;
            "seat20": boolean;
            "seat21": boolean;
            "seat22": boolean;
            "seat23": boolean
        }
    }
}